name: 'MinecraftMaps'
author: 'Redstonneur1256'
version: '1.1'
main: 'fr.redstonneur1256.maps.spigot.MinecraftMaps'
commands:
  minecraftMaps:
    aliases: ['maps']
    description: 'MinecraftMaps configuration command'
    permsision: 'minecraftMaps.admin'